<a href="https://colab.research.google.com/github/Jessica0100/data/blob/main/DiskritisasiData.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
from sklearn.cluster import KMeans
from sklearn.preprocessing import MinMaxScaler
from sklearn.metrics import silhouette_score, accuracy_score
import pandas as pd

# Baca data fitur dan label
df_features = pd.read_excel("/content/drive/MyDrive/data/irisfull.xlsx")
df_class = pd.read_excel("class.xlsx")

# Gabungkan data fitur dan label
df = df_features.copy()
df['class'] = df_class['class']

# Ambil hanya kolom sepal_length
features = df[['sepal_length']]

# Normalisasi fitur
scaler = MinMaxScaler()
scaled_features = scaler.fit_transform(features)

# Clustering KMeans dengan 4 klaster
kmeans = KMeans(n_clusters=4, random_state=42, n_init=10)
kmeans.fit(scaled_features)

# Simpan hasil cluster ke dataframe
df['cluster'] = kmeans.labels_

# Evaluasi
print(f"Jumlah iterasi sampai konvergen: {kmeans.n_iter_}")
print(f"Inertia (SSE): {kmeans.inertia_:.4f}")
sil_score = silhouette_score(scaled_features, kmeans.labels_)
print(f"Silhouette Score: {sil_score:.4f}")

# Pemetaan cluster ke class mayoritas
mapping = (
    df.groupby('cluster')['class']
    .agg(lambda x: x.mode()[0])
    .to_dict()
)
df['predicted_class'] = df['cluster'].map(mapping)

# Hitung akurasi prediksi clustering terhadap label asli
y_true = df['class']
y_pred = df['predicted_class']
acc = accuracy_score(y_true, y_pred)
print(f"\nAkurasi keseluruhan clustering terhadap label asli: {acc:.4%}")

# Tampilkan distribusi cluster per kelas
dist = pd.crosstab(df['class'], df['cluster'], rownames=['Class'], colnames=['Cluster'])
print("\nDistribusi cluster per kelas:")
print(dist)

# Simpan hasil ke Excel
df.to_excel("clus_dis.xlsx", index=False)

# Jika ingin tampilkan semua hasil
pd.set_option('display.max_rows', None)
print(df[['class', 'cluster', 'predicted_class']])

FileNotFoundError: [Errno 2] No such file or directory: 'class.xlsx'

In [2]:
%pip install scikit-learn


import pandas as pd
import numpy as np
from sklearn.preprocessing import StandardScaler
from sklearn.cluster import KMeans

In [4]:
# Baca data
data = pd.read_excel("/content/drive/MyDrive/data/irisfull.xlsx")

print("Data iris")
print(data.head())

Data iris
   id        Class  sepal length  sepal width  petal length  petal width
0   1  Iris-setosa           5.1          3.5           1.4          0.2
1   2  Iris-setosa           4.9          3.0           1.4          0.2
2   3  Iris-setosa           4.7          3.2           1.3          0.2
3   4  Iris-setosa           4.6          3.1           1.5          0.2
4   5  Iris-setosa           5.0          3.6           1.4          0.2


In [6]:
# Ambil hanya kolom sepal_length untuk clustering
X = data[['sepal length']].values

print("\nData iris Sepal Length")
print(X)


Data iris Sepal Length
[[5.1]
 [4.9]
 [4.7]
 [4.6]
 [5. ]
 [5.4]
 [4.6]
 [5. ]
 [4.4]
 [4.9]
 [5.4]
 [4.8]
 [4.8]
 [4.3]
 [5.8]
 [5.7]
 [5.4]
 [5.1]
 [5.7]
 [5.1]
 [5.4]
 [5.1]
 [4.6]
 [5.1]
 [4.8]
 [5. ]
 [5. ]
 [5.2]
 [5.2]
 [4.7]
 [4.8]
 [5.4]
 [5.2]
 [5.5]
 [4.9]
 [5. ]
 [5.5]
 [4.9]
 [4.4]
 [5.1]
 [5. ]
 [4.5]
 [4.4]
 [5. ]
 [5.1]
 [4.8]
 [5.1]
 [4.6]
 [5.3]
 [5. ]
 [7. ]
 [6.4]
 [6.9]
 [5.5]
 [6.5]
 [5.7]
 [6.3]
 [4.9]
 [6.6]
 [5.2]
 [5. ]
 [5.9]
 [6. ]
 [6.1]
 [5.6]
 [6.7]
 [5.6]
 [5.8]
 [6.2]
 [5.6]
 [5.9]
 [6.1]
 [6.3]
 [6.1]
 [6.4]
 [6.6]
 [6.8]
 [6.7]
 [6. ]
 [5.7]
 [5.5]
 [5.5]
 [5.8]
 [6. ]
 [5.4]
 [6. ]
 [6.7]
 [6.3]
 [5.6]
 [5.5]
 [5.5]
 [6.1]
 [5.8]
 [5. ]
 [5.6]
 [5.7]
 [5.7]
 [6.2]
 [5.1]
 [5.7]
 [6.3]
 [5.8]
 [7.1]
 [6.3]
 [6.5]
 [7.6]
 [4.9]
 [7.3]
 [6.7]
 [7.2]
 [6.5]
 [6.4]
 [6.8]
 [5.7]
 [5.8]
 [6.4]
 [6.5]
 [7.7]
 [7.7]
 [6. ]
 [6.9]
 [5.6]
 [7.7]
 [6.3]
 [6.7]
 [7.2]
 [6.2]
 [6.1]
 [6.4]
 [7.2]
 [7.4]
 [7.9]
 [6.4]
 [6.3]
 [6.1]
 [7.7]
 [6.3]
 [6.4]
 [6. ]
 [6

In [7]:
# Normalisasi
scaler = StandardScaler()
X_scaled = scaler.fit_transform(X)
print("\nNormalisasi data Sepal Length")
print(X_scaled)


Normalisasi data Sepal Length
[[-0.90068117]
 [-1.14301691]
 [-1.38535265]
 [-1.50652052]
 [-1.02184904]
 [-0.53717756]
 [-1.50652052]
 [-1.02184904]
 [-1.74885626]
 [-1.14301691]
 [-0.53717756]
 [-1.26418478]
 [-1.26418478]
 [-1.87002413]
 [-0.05250608]
 [-0.17367395]
 [-0.53717756]
 [-0.90068117]
 [-0.17367395]
 [-0.90068117]
 [-0.53717756]
 [-0.90068117]
 [-1.50652052]
 [-0.90068117]
 [-1.26418478]
 [-1.02184904]
 [-1.02184904]
 [-0.7795133 ]
 [-0.7795133 ]
 [-1.38535265]
 [-1.26418478]
 [-0.53717756]
 [-0.7795133 ]
 [-0.41600969]
 [-1.14301691]
 [-1.02184904]
 [-0.41600969]
 [-1.14301691]
 [-1.74885626]
 [-0.90068117]
 [-1.02184904]
 [-1.62768839]
 [-1.74885626]
 [-1.02184904]
 [-0.90068117]
 [-1.26418478]
 [-0.90068117]
 [-1.50652052]
 [-0.65834543]
 [-1.02184904]
 [ 1.40150837]
 [ 0.67450115]
 [ 1.2803405 ]
 [-0.41600969]
 [ 0.79566902]
 [-0.17367395]
 [ 0.55333328]
 [-1.14301691]
 [ 0.91683689]
 [-0.7795133 ]
 [-1.02184904]
 [ 0.06866179]
 [ 0.18982966]
 [ 0.31099753]
 [-0.2948

In [8]:
# Clustering
kms = KMeans(n_clusters=4, random_state=0, n_init="auto").fit(X_scaled)
print("\nHasil label cluster (dengan angka):")
print(kms.labels_)


Hasil label cluster (dengan angka):
[2 2 2 2 2 0 2 2 2 2 0 2 2 2 0 0 0 2 0 2 0 2 2 2 2 2 2 2 2 2 2 0 2 0 2 2 0
 2 2 2 2 2 2 2 2 2 2 2 0 2 1 3 1 0 3 0 3 2 3 2 2 0 0 3 0 3 0 0 3 0 0 3 3 3
 3 3 3 3 0 0 0 0 0 0 0 0 3 3 0 0 0 3 0 2 0 0 0 3 2 0 3 0 1 3 3 1 2 1 3 1 3
 3 3 0 0 3 3 1 1 0 1 0 1 3 3 1 3 3 3 1 1 1 3 3 3 1 3 3 0 1 3 1 0 3 3 3 3 3
 3 0]


In [9]:
# Mapping label angka → huruf
label_mapping = {0:'A', 1:'B', 2:'C', 3:'D'}
cluster_labels_named = [label_mapping[label] for label in kms.labels_]
cluster_labels_named_np = np.array(cluster_labels_named)

# Cetak hasil label dalam bentuk huruf
print("\nHasil label cluster (dengan nama):")
print(cluster_labels_named_np)


Hasil label cluster (dengan nama):
['C' 'C' 'C' 'C' 'C' 'A' 'C' 'C' 'C' 'C' 'A' 'C' 'C' 'C' 'A' 'A' 'A' 'C'
 'A' 'C' 'A' 'C' 'C' 'C' 'C' 'C' 'C' 'C' 'C' 'C' 'C' 'A' 'C' 'A' 'C' 'C'
 'A' 'C' 'C' 'C' 'C' 'C' 'C' 'C' 'C' 'C' 'C' 'C' 'A' 'C' 'B' 'D' 'B' 'A'
 'D' 'A' 'D' 'C' 'D' 'C' 'C' 'A' 'A' 'D' 'A' 'D' 'A' 'A' 'D' 'A' 'A' 'D'
 'D' 'D' 'D' 'D' 'D' 'D' 'A' 'A' 'A' 'A' 'A' 'A' 'A' 'A' 'D' 'D' 'A' 'A'
 'A' 'D' 'A' 'C' 'A' 'A' 'A' 'D' 'C' 'A' 'D' 'A' 'B' 'D' 'D' 'B' 'C' 'B'
 'D' 'B' 'D' 'D' 'D' 'A' 'A' 'D' 'D' 'B' 'B' 'A' 'B' 'A' 'B' 'D' 'D' 'B'
 'D' 'D' 'D' 'B' 'B' 'B' 'D' 'D' 'D' 'B' 'D' 'D' 'A' 'B' 'D' 'B' 'A' 'D'
 'D' 'D' 'D' 'D' 'D' 'A']


In [11]:
# Ganti kolom sepal_length dengan label huruf cluster
data['sepal_length'] = cluster_labels_named_np
print("\nData iris dengan 'sepal_length' diganti huruf cluster:")
print(data)

# Simpan ke CSV
data.to_csv("iris_Diskritisasi.csv", index=False)


Data iris dengan 'sepal_length' diganti huruf cluster:
      id           Class  sepal length  sepal width  petal length  \
0      1     Iris-setosa           5.1          3.5           1.4   
1      2     Iris-setosa           4.9          3.0           1.4   
2      3     Iris-setosa           4.7          3.2           1.3   
3      4     Iris-setosa           4.6          3.1           1.5   
4      5     Iris-setosa           5.0          3.6           1.4   
..   ...             ...           ...          ...           ...   
145  146  Iris-virginica           6.7          3.0           5.2   
146  147  Iris-virginica           6.3          2.5           5.0   
147  148  Iris-virginica           6.5          3.0           5.2   
148  149  Iris-virginica           6.2          3.4           5.4   
149  150  Iris-virginica           5.9          3.0           5.1   

     petal width sepal_length  
0            0.2            C  
1            0.2            C  
2            0.2   

In [17]:
# Baca data
data = pd.read_csv("IRIS_Diskritisasi.csv")

print("Data iris")
print(data.head())

Data iris
   id        Class  sepal length  sepal width  petal length  petal width  \
0   1  Iris-setosa           5.1          3.5           1.4          0.2   
1   2  Iris-setosa           4.9          3.0           1.4          0.2   
2   3  Iris-setosa           4.7          3.2           1.3          0.2   
3   4  Iris-setosa           4.6          3.1           1.5          0.2   
4   5  Iris-setosa           5.0          3.6           1.4          0.2   

  sepal_length  
0            C  
1            C  
2            C  
3            C  
4            C  


In [16]:
# Ambil hanya kolom sepal_width untuk clustering
X = data[['sepal width']].values

print("\nData iris Sepal Width")
print(X)


Data iris Sepal Width
[[3.5]
 [3. ]
 [3.2]
 [3.1]
 [3.6]
 [3.9]
 [3.4]
 [3.4]
 [2.9]
 [3.1]
 [3.7]
 [3.4]
 [3. ]
 [3. ]
 [4. ]
 [4.4]
 [3.9]
 [3.5]
 [3.8]
 [3.8]
 [3.4]
 [3.7]
 [3.6]
 [3.3]
 [3.4]
 [3. ]
 [3.4]
 [3.5]
 [3.4]
 [3.2]
 [3.1]
 [3.4]
 [4.1]
 [4.2]
 [3.1]
 [3.2]
 [3.5]
 [3.1]
 [3. ]
 [3.4]
 [3.5]
 [2.3]
 [3.2]
 [3.5]
 [3.8]
 [3. ]
 [3.8]
 [3.2]
 [3.7]
 [3.3]
 [3.2]
 [3.2]
 [3.1]
 [2.3]
 [2.8]
 [2.8]
 [3.3]
 [2.4]
 [2.9]
 [2.7]
 [2. ]
 [3. ]
 [2.2]
 [2.9]
 [2.9]
 [3.1]
 [3. ]
 [2.7]
 [2.2]
 [2.5]
 [3.2]
 [2.8]
 [2.5]
 [2.8]
 [2.9]
 [3. ]
 [2.8]
 [3. ]
 [2.9]
 [2.6]
 [2.4]
 [2.4]
 [2.7]
 [2.7]
 [3. ]
 [3.4]
 [3.1]
 [2.3]
 [3. ]
 [2.5]
 [2.6]
 [3. ]
 [2.6]
 [2.3]
 [2.7]
 [3. ]
 [2.9]
 [2.9]
 [2.5]
 [2.8]
 [3.3]
 [2.7]
 [3. ]
 [2.9]
 [3. ]
 [3. ]
 [2.5]
 [2.9]
 [2.5]
 [3.6]
 [3.2]
 [2.7]
 [3. ]
 [2.5]
 [2.8]
 [3.2]
 [3. ]
 [3.8]
 [2.6]
 [2.2]
 [3.2]
 [2.8]
 [2.8]
 [2.7]
 [3.3]
 [3.2]
 [2.8]
 [3. ]
 [2.8]
 [3. ]
 [2.8]
 [3.8]
 [2.8]
 [2.8]
 [2.6]
 [3. ]
 [3.4]
 [3.1]
 [3. ]
 [3.

In [18]:
# Normalisasi
scaler = StandardScaler()
X_scaled = scaler.fit_transform(X)
print("\nNormalisasi data Sepal Width")
print(X_scaled)


Normalisasi data Sepal Width
[[ 1.03205722]
 [-0.1249576 ]
 [ 0.33784833]
 [ 0.10644536]
 [ 1.26346019]
 [ 1.95766909]
 [ 0.80065426]
 [ 0.80065426]
 [-0.35636057]
 [ 0.10644536]
 [ 1.49486315]
 [ 0.80065426]
 [-0.1249576 ]
 [-0.1249576 ]
 [ 2.18907205]
 [ 3.11468391]
 [ 1.95766909]
 [ 1.03205722]
 [ 1.72626612]
 [ 1.72626612]
 [ 0.80065426]
 [ 1.49486315]
 [ 1.26346019]
 [ 0.56925129]
 [ 0.80065426]
 [-0.1249576 ]
 [ 0.80065426]
 [ 1.03205722]
 [ 0.80065426]
 [ 0.33784833]
 [ 0.10644536]
 [ 0.80065426]
 [ 2.42047502]
 [ 2.65187798]
 [ 0.10644536]
 [ 0.33784833]
 [ 1.03205722]
 [ 0.10644536]
 [-0.1249576 ]
 [ 0.80065426]
 [ 1.03205722]
 [-1.74477836]
 [ 0.33784833]
 [ 1.03205722]
 [ 1.72626612]
 [-0.1249576 ]
 [ 1.72626612]
 [ 0.33784833]
 [ 1.49486315]
 [ 0.56925129]
 [ 0.33784833]
 [ 0.33784833]
 [ 0.10644536]
 [-1.74477836]
 [-0.58776353]
 [-0.58776353]
 [ 0.56925129]
 [-1.51337539]
 [-0.35636057]
 [-0.8191665 ]
 [-2.43898725]
 [-0.1249576 ]
 [-1.97618132]
 [-0.35636057]
 [-0.35636

In [19]:
# Clustering
kms = KMeans(n_clusters=3, random_state=0, n_init="auto").fit(X_scaled)
print("\nHasil label cluster (dengan angka):")
print(kms.labels_)


Hasil label cluster (dengan angka):
[1 2 2 2 1 1 1 1 2 2 1 1 2 2 1 1 1 1 1 1 1 1 1 2 1 2 1 1 1 2 2 1 1 1 2 2 1
 2 2 1 1 0 2 1 1 2 1 2 1 2 2 2 2 0 0 0 2 0 2 0 0 2 0 2 2 2 2 0 0 0 2 0 0 0
 2 2 0 2 2 0 0 0 0 0 2 1 2 0 2 0 0 2 0 0 0 2 2 2 0 0 2 0 2 2 2 2 0 2 0 1 2
 0 2 0 0 2 2 1 0 0 2 0 0 0 2 2 0 2 0 2 0 1 0 0 0 2 1 2 2 2 2 2 0 2 2 2 0 2
 1 2]


In [20]:
# Mapping label angka → huruf
label_mapping = {0:'A', 1:'B', 2:'C', 3:'D'}
cluster_labels_named = [label_mapping[label] for label in kms.labels_]
cluster_labels_named_np = np.array(cluster_labels_named)

# Cetak hasil label dalam bentuk huruf
print("\nHasil label cluster (dengan nama):")
print(cluster_labels_named_np)


Hasil label cluster (dengan nama):
['B' 'C' 'C' 'C' 'B' 'B' 'B' 'B' 'C' 'C' 'B' 'B' 'C' 'C' 'B' 'B' 'B' 'B'
 'B' 'B' 'B' 'B' 'B' 'C' 'B' 'C' 'B' 'B' 'B' 'C' 'C' 'B' 'B' 'B' 'C' 'C'
 'B' 'C' 'C' 'B' 'B' 'A' 'C' 'B' 'B' 'C' 'B' 'C' 'B' 'C' 'C' 'C' 'C' 'A'
 'A' 'A' 'C' 'A' 'C' 'A' 'A' 'C' 'A' 'C' 'C' 'C' 'C' 'A' 'A' 'A' 'C' 'A'
 'A' 'A' 'C' 'C' 'A' 'C' 'C' 'A' 'A' 'A' 'A' 'A' 'C' 'B' 'C' 'A' 'C' 'A'
 'A' 'C' 'A' 'A' 'A' 'C' 'C' 'C' 'A' 'A' 'C' 'A' 'C' 'C' 'C' 'C' 'A' 'C'
 'A' 'B' 'C' 'A' 'C' 'A' 'A' 'C' 'C' 'B' 'A' 'A' 'C' 'A' 'A' 'A' 'C' 'C'
 'A' 'C' 'A' 'C' 'A' 'B' 'A' 'A' 'A' 'C' 'B' 'C' 'C' 'C' 'C' 'C' 'A' 'C'
 'C' 'C' 'A' 'C' 'B' 'C']


In [24]:
# Ganti kolom sepal_width dengan label huruf cluster
data['sepal width'] = cluster_labels_named_np
print("\nData iris dengan 'sepal width' diganti huruf cluster:")
print(data)

# Simpan ke excel
data.to_excel("iris_Diskritisasi.xlsx", index=False)


Data iris dengan 'sepal width' diganti huruf cluster:
      id           Class  sepal length sepal width  petal length  petal width  \
0      1     Iris-setosa           5.1           B           1.4          0.2   
1      2     Iris-setosa           4.9           C           1.4          0.2   
2      3     Iris-setosa           4.7           C           1.3          0.2   
3      4     Iris-setosa           4.6           C           1.5          0.2   
4      5     Iris-setosa           5.0           B           1.4          0.2   
..   ...             ...           ...         ...           ...          ...   
145  146  Iris-virginica           6.7           C           5.2          2.3   
146  147  Iris-virginica           6.3           A           5.0          1.9   
147  148  Iris-virginica           6.5           C           5.2          2.0   
148  149  Iris-virginica           6.2           B           5.4          2.3   
149  150  Iris-virginica           5.9           C    

In [25]:
# Baca data
data = pd.read_excel("iris_Diskritisasi.xlsx")

print("Data iris")
print(data.head())

Data iris
   id        Class  sepal length sepal width  petal length  petal width  \
0   1  Iris-setosa           5.1           B           1.4          0.2   
1   2  Iris-setosa           4.9           C           1.4          0.2   
2   3  Iris-setosa           4.7           C           1.3          0.2   
3   4  Iris-setosa           4.6           C           1.5          0.2   
4   5  Iris-setosa           5.0           B           1.4          0.2   

  sepal_length  
0            C  
1            C  
2            C  
3            C  
4            C  


In [26]:
# Ambil hanya kolom petal_length untuk clustering
X = data[['petal length']].values

print("\nData iris Petal Length")
print(X)


Data iris Petal Length
[[1.4]
 [1.4]
 [1.3]
 [1.5]
 [1.4]
 [1.7]
 [1.4]
 [1.5]
 [1.4]
 [1.5]
 [1.5]
 [1.6]
 [1.4]
 [1.1]
 [1.2]
 [1.5]
 [1.3]
 [1.4]
 [1.7]
 [1.5]
 [1.7]
 [1.5]
 [1. ]
 [1.7]
 [1.9]
 [1.6]
 [1.6]
 [1.5]
 [1.4]
 [1.6]
 [1.6]
 [1.5]
 [1.5]
 [1.4]
 [1.5]
 [1.2]
 [1.3]
 [1.5]
 [1.3]
 [1.5]
 [1.3]
 [1.3]
 [1.3]
 [1.6]
 [1.9]
 [1.4]
 [1.6]
 [1.4]
 [1.5]
 [1.4]
 [4.7]
 [4.5]
 [4.9]
 [4. ]
 [4.6]
 [4.5]
 [4.7]
 [3.3]
 [4.6]
 [3.9]
 [3.5]
 [4.2]
 [4. ]
 [4.7]
 [3.6]
 [4.4]
 [4.5]
 [4.1]
 [4.5]
 [3.9]
 [4.8]
 [4. ]
 [4.9]
 [4.7]
 [4.3]
 [4.4]
 [4.8]
 [5. ]
 [4.5]
 [3.5]
 [3.8]
 [3.7]
 [3.9]
 [5.1]
 [4.5]
 [4.5]
 [4.7]
 [4.4]
 [4.1]
 [4. ]
 [4.4]
 [4.6]
 [4. ]
 [3.3]
 [4.2]
 [4.2]
 [4.2]
 [4.3]
 [3. ]
 [4.1]
 [6. ]
 [5.1]
 [5.9]
 [5.6]
 [5.8]
 [6.6]
 [4.5]
 [6.3]
 [5.8]
 [6.1]
 [5.1]
 [5.3]
 [5.5]
 [5. ]
 [5.1]
 [5.3]
 [5.5]
 [6.7]
 [6.9]
 [5. ]
 [5.7]
 [4.9]
 [6.7]
 [4.9]
 [5.7]
 [6. ]
 [4.8]
 [4.9]
 [5.6]
 [5.8]
 [6.1]
 [6.4]
 [5.6]
 [5.1]
 [5.6]
 [6.1]
 [5.6]
 [5.5]
 [4.8]
 [5

In [27]:
# Normalisasi
scaler = StandardScaler()
X_scaled = scaler.fit_transform(X)
print("\nNormalisasi data Petal Length")
print(X_scaled)


Normalisasi data Petal Length
[[-1.3412724 ]
 [-1.3412724 ]
 [-1.39813811]
 [-1.2844067 ]
 [-1.3412724 ]
 [-1.17067529]
 [-1.3412724 ]
 [-1.2844067 ]
 [-1.3412724 ]
 [-1.2844067 ]
 [-1.2844067 ]
 [-1.227541  ]
 [-1.3412724 ]
 [-1.51186952]
 [-1.45500381]
 [-1.2844067 ]
 [-1.39813811]
 [-1.3412724 ]
 [-1.17067529]
 [-1.2844067 ]
 [-1.17067529]
 [-1.2844067 ]
 [-1.56873522]
 [-1.17067529]
 [-1.05694388]
 [-1.227541  ]
 [-1.227541  ]
 [-1.2844067 ]
 [-1.3412724 ]
 [-1.227541  ]
 [-1.227541  ]
 [-1.2844067 ]
 [-1.2844067 ]
 [-1.3412724 ]
 [-1.2844067 ]
 [-1.45500381]
 [-1.39813811]
 [-1.2844067 ]
 [-1.39813811]
 [-1.2844067 ]
 [-1.39813811]
 [-1.39813811]
 [-1.39813811]
 [-1.227541  ]
 [-1.05694388]
 [-1.3412724 ]
 [-1.227541  ]
 [-1.3412724 ]
 [-1.2844067 ]
 [-1.3412724 ]
 [ 0.53529583]
 [ 0.42156442]
 [ 0.64902723]
 [ 0.1372359 ]
 [ 0.47843012]
 [ 0.42156442]
 [ 0.53529583]
 [-0.26082403]
 [ 0.47843012]
 [ 0.08037019]
 [-0.14709262]
 [ 0.25096731]
 [ 0.1372359 ]
 [ 0.53529583]
 [-0.0902

In [28]:
# Clustering
kms = KMeans(n_clusters=4, random_state=0, n_init="auto").fit(X_scaled)
print("\nHasil label cluster (dengan angka):")
print(kms.labels_)


Hasil label cluster (dengan angka):
[1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
 1 1 1 1 1 1 1 1 1 1 1 1 1 2 2 2 0 2 2 2 0 2 0 0 0 0 2 0 2 2 0 2 0 2 0 2 2
 0 2 2 2 2 0 0 0 0 2 2 2 2 2 0 0 2 2 0 0 0 0 0 0 0 0 3 2 3 3 3 3 2 3 3 3 2
 2 3 2 2 2 3 3 3 2 3 2 3 2 3 3 2 2 3 3 3 3 3 2 3 3 3 3 2 3 3 2 2 3 3 2 2 2
 3 2]


In [29]:
# Mapping label angka → huruf
label_mapping = {0:'A', 1:'B', 2:'C', 3:'D'}
cluster_labels_named = [label_mapping[label] for label in kms.labels_]
cluster_labels_named_np = np.array(cluster_labels_named)

# Cetak hasil label dalam bentuk huruf
print("\nHasil label cluster (dengan nama):")
print(cluster_labels_named_np)


Hasil label cluster (dengan nama):
['B' 'B' 'B' 'B' 'B' 'B' 'B' 'B' 'B' 'B' 'B' 'B' 'B' 'B' 'B' 'B' 'B' 'B'
 'B' 'B' 'B' 'B' 'B' 'B' 'B' 'B' 'B' 'B' 'B' 'B' 'B' 'B' 'B' 'B' 'B' 'B'
 'B' 'B' 'B' 'B' 'B' 'B' 'B' 'B' 'B' 'B' 'B' 'B' 'B' 'B' 'C' 'C' 'C' 'A'
 'C' 'C' 'C' 'A' 'C' 'A' 'A' 'A' 'A' 'C' 'A' 'C' 'C' 'A' 'C' 'A' 'C' 'A'
 'C' 'C' 'A' 'C' 'C' 'C' 'C' 'A' 'A' 'A' 'A' 'C' 'C' 'C' 'C' 'C' 'A' 'A'
 'C' 'C' 'A' 'A' 'A' 'A' 'A' 'A' 'A' 'A' 'D' 'C' 'D' 'D' 'D' 'D' 'C' 'D'
 'D' 'D' 'C' 'C' 'D' 'C' 'C' 'C' 'D' 'D' 'D' 'C' 'D' 'C' 'D' 'C' 'D' 'D'
 'C' 'C' 'D' 'D' 'D' 'D' 'D' 'C' 'D' 'D' 'D' 'D' 'C' 'D' 'D' 'C' 'C' 'D'
 'D' 'C' 'C' 'C' 'D' 'C']


In [31]:
# Ganti kolom petal_length dengan label huruf cluster
data['petal_length'] = cluster_labels_named_np
print("\nData iris dengan 'petal length' diganti huruf cluster:")
print(data)

# Simpan ke excel
data.to_excel("iris_Diskritisasi.xlsx", index=False)


Data iris dengan 'petal length' diganti huruf cluster:
      id           Class  sepal length sepal width  petal length  petal width  \
0      1     Iris-setosa           5.1           B           1.4          0.2   
1      2     Iris-setosa           4.9           C           1.4          0.2   
2      3     Iris-setosa           4.7           C           1.3          0.2   
3      4     Iris-setosa           4.6           C           1.5          0.2   
4      5     Iris-setosa           5.0           B           1.4          0.2   
..   ...             ...           ...         ...           ...          ...   
145  146  Iris-virginica           6.7           C           5.2          2.3   
146  147  Iris-virginica           6.3           A           5.0          1.9   
147  148  Iris-virginica           6.5           C           5.2          2.0   
148  149  Iris-virginica           6.2           B           5.4          2.3   
149  150  Iris-virginica           5.9           C   

In [33]:
# Baca data
data = pd.read_excel("/content/drive/MyDrive/data/irisfull.xlsx")

print("Data iris")
print(data.head())

Data iris
   id        Class  sepal length  sepal width  petal length  petal width
0   1  Iris-setosa           5.1          3.5           1.4          0.2
1   2  Iris-setosa           4.9          3.0           1.4          0.2
2   3  Iris-setosa           4.7          3.2           1.3          0.2
3   4  Iris-setosa           4.6          3.1           1.5          0.2
4   5  Iris-setosa           5.0          3.6           1.4          0.2


In [34]:
# Ambil hanya kolom petal_width untuk clustering
X = data[['petal width']].values

print("\nData iris Petal Width")
print(X)


Data iris Petal Width
[[0.2]
 [0.2]
 [0.2]
 [0.2]
 [0.2]
 [0.4]
 [0.3]
 [0.2]
 [0.2]
 [0.1]
 [0.2]
 [0.2]
 [0.1]
 [0.1]
 [0.2]
 [0.4]
 [0.4]
 [0.3]
 [0.3]
 [0.3]
 [0.2]
 [0.4]
 [0.2]
 [0.5]
 [0.2]
 [0.2]
 [0.4]
 [0.2]
 [0.2]
 [0.2]
 [0.2]
 [0.4]
 [0.1]
 [0.2]
 [0.1]
 [0.2]
 [0.2]
 [0.1]
 [0.2]
 [0.2]
 [0.3]
 [0.3]
 [0.2]
 [0.6]
 [0.4]
 [0.3]
 [0.2]
 [0.2]
 [0.2]
 [0.2]
 [1.4]
 [1.5]
 [1.5]
 [1.3]
 [1.5]
 [1.3]
 [1.6]
 [1. ]
 [1.3]
 [1.4]
 [1. ]
 [1.5]
 [1. ]
 [1.4]
 [1.3]
 [1.4]
 [1.5]
 [1. ]
 [1.5]
 [1.1]
 [1.8]
 [1.3]
 [1.5]
 [1.2]
 [1.3]
 [1.4]
 [1.4]
 [1.7]
 [1.5]
 [1. ]
 [1.1]
 [1. ]
 [1.2]
 [1.6]
 [1.5]
 [1.6]
 [1.5]
 [1.3]
 [1.3]
 [1.3]
 [1.2]
 [1.4]
 [1.2]
 [1. ]
 [1.3]
 [1.2]
 [1.3]
 [1.3]
 [1.1]
 [1.3]
 [2.5]
 [1.9]
 [2.1]
 [1.8]
 [2.2]
 [2.1]
 [1.7]
 [1.8]
 [1.8]
 [2.5]
 [2. ]
 [1.9]
 [2.1]
 [2. ]
 [2.4]
 [2.3]
 [1.8]
 [2.2]
 [2.3]
 [1.5]
 [2.3]
 [2. ]
 [2. ]
 [1.8]
 [2.1]
 [1.8]
 [1.8]
 [1.8]
 [2.1]
 [1.6]
 [1.9]
 [2. ]
 [2.2]
 [1.5]
 [1.4]
 [2.3]
 [2.4]
 [1.8]
 [1.8]
 [2.

In [35]:
# Normalisasi
scaler = StandardScaler()
X_scaled = scaler.fit_transform(X)
print("\nNormalisasi data Petal Width")
print(X_scaled)


Normalisasi data Petal Width
[[-1.31297673]
 [-1.31297673]
 [-1.31297673]
 [-1.31297673]
 [-1.31297673]
 [-1.05003079]
 [-1.18150376]
 [-1.31297673]
 [-1.31297673]
 [-1.4444497 ]
 [-1.31297673]
 [-1.31297673]
 [-1.4444497 ]
 [-1.4444497 ]
 [-1.31297673]
 [-1.05003079]
 [-1.05003079]
 [-1.18150376]
 [-1.18150376]
 [-1.18150376]
 [-1.31297673]
 [-1.05003079]
 [-1.31297673]
 [-0.91855782]
 [-1.31297673]
 [-1.31297673]
 [-1.05003079]
 [-1.31297673]
 [-1.31297673]
 [-1.31297673]
 [-1.31297673]
 [-1.05003079]
 [-1.4444497 ]
 [-1.31297673]
 [-1.4444497 ]
 [-1.31297673]
 [-1.31297673]
 [-1.4444497 ]
 [-1.31297673]
 [-1.31297673]
 [-1.18150376]
 [-1.18150376]
 [-1.31297673]
 [-0.78708485]
 [-1.05003079]
 [-1.18150376]
 [-1.31297673]
 [-1.31297673]
 [-1.31297673]
 [-1.31297673]
 [ 0.26469891]
 [ 0.39617188]
 [ 0.39617188]
 [ 0.13322594]
 [ 0.39617188]
 [ 0.13322594]
 [ 0.52764485]
 [-0.26119297]
 [ 0.13322594]
 [ 0.26469891]
 [-0.26119297]
 [ 0.39617188]
 [-0.26119297]
 [ 0.26469891]
 [ 0.13322

In [36]:
# Clustering
kms = KMeans(n_clusters=3, random_state=0, n_init="auto").fit(X_scaled)
print("\nHasil label cluster (dengan angka):")
print(kms.labels_)


Hasil label cluster (dengan angka):
[2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2
 2 2 2 2 2 2 2 2 2 2 2 2 2 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0
 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 1 1 1 1 1 1 1 1 1 1
 1 1 1 1 1 1 1 1 0 1 1 1 1 1 1 1 1 1 0 1 1 1 0 0 1 1 1 1 1 1 1 1 1 1 1 1 1
 1 1]


In [37]:
# Mapping label angka → huruf
label_mapping = {0:'A', 1:'B', 2:'C', 3:'D'}
cluster_labels_named = [label_mapping[label] for label in kms.labels_]
cluster_labels_named_np = np.array(cluster_labels_named)

# Cetak hasil label dalam bentuk huruf
print("\nHasil label cluster (dengan nama):")
print(cluster_labels_named_np)


Hasil label cluster (dengan nama):
['C' 'C' 'C' 'C' 'C' 'C' 'C' 'C' 'C' 'C' 'C' 'C' 'C' 'C' 'C' 'C' 'C' 'C'
 'C' 'C' 'C' 'C' 'C' 'C' 'C' 'C' 'C' 'C' 'C' 'C' 'C' 'C' 'C' 'C' 'C' 'C'
 'C' 'C' 'C' 'C' 'C' 'C' 'C' 'C' 'C' 'C' 'C' 'C' 'C' 'C' 'A' 'A' 'A' 'A'
 'A' 'A' 'A' 'A' 'A' 'A' 'A' 'A' 'A' 'A' 'A' 'A' 'A' 'A' 'A' 'A' 'B' 'A'
 'A' 'A' 'A' 'A' 'A' 'B' 'A' 'A' 'A' 'A' 'A' 'A' 'A' 'A' 'A' 'A' 'A' 'A'
 'A' 'A' 'A' 'A' 'A' 'A' 'A' 'A' 'A' 'A' 'B' 'B' 'B' 'B' 'B' 'B' 'B' 'B'
 'B' 'B' 'B' 'B' 'B' 'B' 'B' 'B' 'B' 'B' 'B' 'A' 'B' 'B' 'B' 'B' 'B' 'B'
 'B' 'B' 'B' 'A' 'B' 'B' 'B' 'A' 'A' 'B' 'B' 'B' 'B' 'B' 'B' 'B' 'B' 'B'
 'B' 'B' 'B' 'B' 'B' 'B']


In [38]:
# Ganti kolom petal_width dengan label huruf cluster
data['petal_width'] = cluster_labels_named_np
print("\nData IRIS dengan 'petal_width' diganti huruf cluster:")
print(data)

# Simpan ke excel
data.to_excel("iris_Diskritisasi.xlsx", index=False)


Data IRIS dengan 'petal_width' diganti huruf cluster:
      id           Class  sepal length  sepal width  petal length  \
0      1     Iris-setosa           5.1          3.5           1.4   
1      2     Iris-setosa           4.9          3.0           1.4   
2      3     Iris-setosa           4.7          3.2           1.3   
3      4     Iris-setosa           4.6          3.1           1.5   
4      5     Iris-setosa           5.0          3.6           1.4   
..   ...             ...           ...          ...           ...   
145  146  Iris-virginica           6.7          3.0           5.2   
146  147  Iris-virginica           6.3          2.5           5.0   
147  148  Iris-virginica           6.5          3.0           5.2   
148  149  Iris-virginica           6.2          3.4           5.4   
149  150  Iris-virginica           5.9          3.0           5.1   

     petal width petal_width  
0            0.2           C  
1            0.2           C  
2            0.2       

In [39]:
# Baca data
data = pd.read_excel("/content/drive/MyDrive/data/irisfull.xlsx")

print("Data iris Diskritisasi")
print(data)

Data iris Diskritisasi
      id           Class  sepal length  sepal width  petal length  petal width
0      1     Iris-setosa           5.1          3.5           1.4          0.2
1      2     Iris-setosa           4.9          3.0           1.4          0.2
2      3     Iris-setosa           4.7          3.2           1.3          0.2
3      4     Iris-setosa           4.6          3.1           1.5          0.2
4      5     Iris-setosa           5.0          3.6           1.4          0.2
..   ...             ...           ...          ...           ...          ...
145  146  Iris-virginica           6.7          3.0           5.2          2.3
146  147  Iris-virginica           6.3          2.5           5.0          1.9
147  148  Iris-virginica           6.5          3.0           5.2          2.0
148  149  Iris-virginica           6.2          3.4           5.4          2.3
149  150  Iris-virginica           5.9          3.0           5.1          1.8

[150 rows x 6 columns]


In [43]:
# Baca data
data = pd.read_excel("iris_Diskritisasi.xlsx")

# Drop the 'class' column, ignoring the error if it's not found
data = data.drop(columns=['class'], errors='ignore')

print("Data iris Diskritisasi")
print(data)

Data iris Diskritisasi
      id           Class  sepal length  sepal width  petal length  \
0      1     Iris-setosa           5.1          3.5           1.4   
1      2     Iris-setosa           4.9          3.0           1.4   
2      3     Iris-setosa           4.7          3.2           1.3   
3      4     Iris-setosa           4.6          3.1           1.5   
4      5     Iris-setosa           5.0          3.6           1.4   
..   ...             ...           ...          ...           ...   
145  146  Iris-virginica           6.7          3.0           5.2   
146  147  Iris-virginica           6.3          2.5           5.0   
147  148  Iris-virginica           6.5          3.0           5.2   
148  149  Iris-virginica           6.2          3.4           5.4   
149  150  Iris-virginica           5.9          3.0           5.1   

     petal width petal_width  
0            0.2           C  
1            0.2           C  
2            0.2           C  
3            0.2        

In [44]:
# Import Library
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.naive_bayes import CategoricalNB
from sklearn.preprocessing import OrdinalEncoder
from sklearn.metrics import confusion_matrix, accuracy_score

In [45]:
# 1. Baca data
dataset = pd.read_excel('/content/iris_Diskritisasi.xlsx')
print("=== DATA AWAL SEBELUM HAPUS OUTLIER ===")
dataset

=== DATA AWAL SEBELUM HAPUS OUTLIER ===


id           Class  sepal length  sepal width  petal length  \
0      1     Iris-setosa           5.1          3.5           1.4   
1      2     Iris-setosa           4.9          3.0           1.4   
2      3     Iris-setosa           4.7          3.2           1.3   
3      4     Iris-setosa           4.6          3.1           1.5   
4      5     Iris-setosa           5.0          3.6           1.4   
..   ...             ...           ...          ...           ...   
145  146  Iris-virginica           6.7          3.0           5.2   
146  147  Iris-virginica           6.3          2.5           5.0   
147  148  Iris-virginica           6.5          3.0           5.2   
148  149  Iris-virginica           6.2          3.4           5.4   
149  150  Iris-virginica           5.9          3.0           5.1   

     petal width petal_width  
0            0.2           C  
1            0.2           C  
2            0.2           C  
3            0.2           C  
4            0.2           C  
..           ...         ...  
145          2.3           B  
146          1.9           B  
147          2.0           B  
148          2.3           B  
149          1.8           B  

[150 rows x 7 columns]

In [47]:
# Penghapusan outlier: buang baris dengan kategori ekstrem (misal: 'A' pada sepal_width)
dataset_outlier_removed = dataset[dataset['sepal width'] != 'A']

print("Data Setelah Outlier Removal:")
dataset_outlier_removed

Data Setelah Outlier Removal:


id           Class  sepal length  sepal width  petal length  \
0      1     Iris-setosa           5.1          3.5           1.4   
1      2     Iris-setosa           4.9          3.0           1.4   
2      3     Iris-setosa           4.7          3.2           1.3   
3      4     Iris-setosa           4.6          3.1           1.5   
4      5     Iris-setosa           5.0          3.6           1.4   
..   ...             ...           ...          ...           ...   
145  146  Iris-virginica           6.7          3.0           5.2   
146  147  Iris-virginica           6.3          2.5           5.0   
147  148  Iris-virginica           6.5          3.0           5.2   
148  149  Iris-virginica           6.2          3.4           5.4   
149  150  Iris-virginica           5.9          3.0           5.1   

     petal width petal_width  
0            0.2           C  
1            0.2           C  
2            0.2           C  
3            0.2           C  
4            0.2           C  
..           ...         ...  
145          2.3           B  
146          1.9           B  
147          2.0           B  
148          2.3           B  
149          1.8           B  

[150 rows x 7 columns]